services:
  - type: web
    name: hostel-api
    runtime: node
    rootDir: .
    buildCommand: npm install && npx prisma@7.4.2 generate --schema=./prisma/schema.prisma && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_OPTIONS
        value: --max-old-space-size=1024
